### ISSUE TITLE
Support cli args to establish DB connection

### ISSUE THREAD

**Issue by dbarnett** [kareemmahlees/tablex#46]
Could there be an option to pass a DB path to TableX as a cli argument and have it directly open into a connection to that DB path, as an alternative to opening to the landing page and then going through the UI to "Start a connection" > "Select a Database Driver" > enter connection details > "Connect"?

For example, allowing you to run commands like:
```shell
table-x mydb.sqlite
table-x postgresql://localhost:5432/mydb
```
?

**Comment by dbarnett** [comment]
Would also need to figure out if this connection somehow gets a name and gets saved in the list of known connections or what. Personally when I was working with SQLite files for a particular tool, I found it cumbersome picking a name and adding it to a persisted global list of TableX's connections and would've preferred to just invoke `table-x ./somefile.sqlite` any time I wanted to view it without having the connection persisted to open it from the UI in a later TableX session.

**Comment by kareemmahlees** [comment]
Yoo !
I just implemented this and the assets are building as web speak 🚀 .
You will now be able to do something like:
```shell
$ TableX sqlite:./test.db --conn-name test --save
```

**Comment by dbarnett** [comment]
Yay, thanks! Just tried it out (finally) and it works great.

One nice-to-have: it doesn't seem to interpret homedir-relative paths like `sqlite:~/some/path` properly (but does work fine as `sqlite:$HOME/some/path`, at least in my terminal).

**Comment by kareemmahlees** [comment]
> One nice-to-have: it doesn't seem to interpret homedir-relative paths like sqlite:~/some/path properly (but does work fine as sqlite:$HOME/some/path, at least in my terminal).

[Fixed](https://github.com/kareemmahlees/tablex/pull/88) and coming in the next release 🚀.
