### ISSUE TITLE
No back button 

### ISSUE THREAD

**Issue by dbarnett** [kareemmahlees/tablex#48]
I noticed when I pick one connection I didn't see any way to navigate back, like close that connection and return to the connections menu, without closing and reopening the TableX app. Should there be some way to close connections and navigate back?

**Comment by kareemmahlees** [comment]
You might want to checkout the command palette `Ctrl/Cmd + K `, it has an option to navigate back to the connections or create a new connection + the API docs.
I know it is not the most versatile way of navigating backwards and probably a back btn would be more suitable.
